#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Runs all .json or .js files through pythons json lint tool before commiting,
# to make sure that you don't commit broken json objects.
# npx ajv runs validations for commited json file based on validation schema

git_dir=$(git rev-parse --show-toplevel)

for file in $(git diff-index --name-only --diff-filter=ACM --cached HEAD -- \
    | grep -P '\.((js)|(json))$'); do
    if [ $? -ne 0 ] ; then
        echo "Lint check of JSON object failed. Your changes were not commited."
        echo "in $git_dir/$file:"
        python -mjson.tool $file
        exit 1
    fi
    filename="$(basename $file)"
    case $file in (*moz*)
        npx ajv -s validation-schema/$filename -d $file --strict=false;
    esac
done
